apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-binding
subjects:
  - kind: User
    name: privilegeduser
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: privileged
  apiGroup: rbac.authorization.k8s.io