apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-only-binding
subjects:
  - kind: User
    name: viewuser
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view-only
  apiGroup: rbac.authorization.k8s.io